### ISSUE TITLE
support for the other compiler?

### ISSUE THREAD

**Issue by minux** [ianlancetaylor/demangle#1]
do you intend for this package to also support
the other C++ compiler out there?

There isn't much documentation on its ABI, and
the only open source demangler I could find is
in wine, but it's not complete and doesn't support
C++11. clang has almost complete support for
name mangling for that ABI, but there isn't a
demangler.

Thanks.

**Comment by ianlancetaylor** [comment]
I don't intend to write code to demangle symbols for any other compilers.  That's not something I find interesting.

I'd be willing to look at patches if somebody would find that to be useful.
